"""entry table

Revision ID: 416adcf43535
Revises: f993a72fe694
Create Date: 2021-11-29 15:02:47.384911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416adcf43535'
down_revision = 'f993a72fe694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_date'), 'entry', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_date'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
